# Generated by Django 5.2.1 on 2026-06-21 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('ci', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('licencia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'conductor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('ci', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.IntegerField(primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('precio_ruta', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rutas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('placa', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('capacidad_asientos', models.IntegerField(blank=True, null=True)),
                ('id_estado', models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logistica.estado')),
            ],
            options={
                'db_table': 'flota',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_viaje', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('placa', models.ForeignKey(blank=True, db_column='placa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logistica.bus')),
                ('id_ruta', models.ForeignKey(blank=True, db_column='id_ruta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logistica.ruta')),
            ],
            options={
                'db_table': 'viaje',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_asiento', models.IntegerField()),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('placa', models.ForeignKey(db_column='placa', on_delete=django.db.models.deletion.DO_NOTHING, to='logistica.bus')),
            ],
            options={
                'db_table': 'asiento',
                'managed': True,
                'unique_together': {('nro_asiento', 'placa')},
            },
        ),
        migrations.CreateModel(
            name='ViajeConductor',
            fields=[
                ('id_viaje', models.ForeignKey(db_column='id_viaje', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='logistica.horario')),
                ('ci_conductor', models.ForeignKey(db_column='ci_conductor', on_delete=django.db.models.deletion.DO_NOTHING, to='logistica.conductor')),
            ],
            options={
                'db_table': 'viaje_conductor',
                'managed': True,
                'unique_together': {('id_viaje', 'ci_conductor')},
            },
        ),
    ]
