# Generated by Django 5.2.1 on 2026-07-06 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraAsistenteIA',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('consulta', models.TextField()),
                ('respuesta', models.TextField()),
                ('tipo_consulta', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_asistente_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bitacora_asistente_ia',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
