# Generated by Django 6.0.4 on 2026-05-03 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('pk', models.CompositePrimaryKey('nro_asiento', 'placa', blank=True, editable=False, primary_key=True, serialize=False)),
                ('nro_asiento', models.IntegerField()),
                ('piso', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ci', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('ci', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('licencia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'conductor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('nro_encomienda', models.IntegerField(primary_key=True, serialize=False)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion_carga', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'encomienda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('nr_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('total_factura', models.IntegerField()),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flota',
            fields=[
                ('placa', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('capacidad_asientos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecios',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('id_ruta', models.IntegerField(blank=True, null=True)),
                ('precio_viejo', models.IntegerField(blank=True, null=True)),
                ('precio_nuevo', models.IntegerField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial_precios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id_pasaje', models.AutoField(primary_key=True, serialize=False)),
                ('precio_final', models.IntegerField(blank=True, null=True)),
                ('estado_pasaje', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_pasajero', models.CharField(max_length=100)),
                ('ci_pasajero', models.IntegerField(blank=True, null=True)),
                ('telefono_pasajero', models.CharField(max_length=20)),
                ('nro_asiento', models.IntegerField(blank=True, null=True)),
                ('placa_bus', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'pasaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id_ruta', models.IntegerField(primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('precio_ruta', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rutas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEncomienda',
            fields=[
                ('id_encomienda', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_inicial', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_encomienda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPasajero',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tipo_pasajero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
            options={
                'db_table': 'viaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViajeConductor',
            fields=[
                ('pk', models.CompositePrimaryKey('id_viaje', 'ci_conductor', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'viaje_conductor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_recuperacion', models.EmailField(blank=True, max_length=254, null=True)),
                ('es_password_temporal', models.BooleanField(default=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueado', models.BooleanField(default=False)),
                ('token_recuperacion', models.CharField(blank=True, max_length=100, null=True)),
                ('token_expira', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil_admin',
            },
        ),
    ]
