# Generated by Django 6.0.4 on 2026-05-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_bitacora'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='modulo',
            field=models.CharField(default='sistema', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfiladmin',
            name='permisos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='perfiladmin',
            name='rol',
            field=models.CharField(choices=[('superusuario', 'Super Usuario'), ('subusuario', 'Sub Usuario')], default='subusuario', max_length=20),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='bitacora',
            table='bitacora',
        ),
    ]
