# Generated by Django 5.2.1 on 2026-06-21 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Encomienda',
            fields=[
                ('id_encomienda', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_inicial', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_encomienda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('nro_encomienda', models.IntegerField(primary_key=True, serialize=False)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion_carga', models.CharField(blank=True, max_length=200, null=True)),
                ('ci_remitente', models.ForeignKey(blank=True, db_column='ci_remitente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logistica.pasajero')),
                ('id_detalle_venta', models.ForeignKey(blank=True, db_column='id_detalle_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.detalleventa')),
                ('id_viaje', models.ForeignKey(blank=True, db_column='id_viaje', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logistica.horario')),
                ('id_encomienda', models.ForeignKey(blank=True, db_column='id_encomienda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='encomiendas.tipo_encomienda')),
            ],
            options={
                'db_table': 'encomienda',
                'managed': True,
            },
        ),
    ]
