# Generated by Django 5.2.1 on 2026-06-21 22:40

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('accion', models.CharField(max_length=20)),
                ('modulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'bitacora',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('superusuario', 'Super Usuario'), ('subusuario', 'Sub Usuario')], default='subusuario', max_length=20)),
                ('correo_recuperacion', models.EmailField(blank=True, max_length=254, null=True)),
                ('es_password_temporal', models.BooleanField(default=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueado', models.BooleanField(default=False)),
                ('token_recuperacion', models.CharField(blank=True, max_length=100, null=True)),
                ('token_expira', models.DateTimeField(blank=True, null=True)),
                ('permisos', models.JSONField(blank=True, default=dict)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil_admin',
            },
        ),
    ]
