# Generated by Django 5.2.1 on 2026-06-21 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPasajero',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tipo_pasajero',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('nr_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('total_factura', models.IntegerField()),
                ('ci_cliente', models.ForeignKey(blank=True, db_column='ci_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logistica.pasajero')),
            ],
            options={
                'db_table': 'factura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.IntegerField(blank=True, null=True)),
                ('nr_factura', models.ForeignKey(blank=True, db_column='nr_factura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.factura')),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id_pasaje', models.AutoField(primary_key=True, serialize=False)),
                ('precio_final', models.IntegerField(blank=True, null=True)),
                ('estado_pasaje', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_pasajero', models.CharField(max_length=100)),
                ('ci_pasajero', models.IntegerField(blank=True, null=True)),
                ('telefono_pasajero', models.CharField(max_length=20)),
                ('nro_asiento', models.IntegerField(blank=True, null=True)),
                ('placa_bus', models.CharField(blank=True, max_length=20, null=True)),
                ('id_detalle_venta', models.ForeignKey(blank=True, db_column='id_detalle_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.detalleventa')),
                ('id_viaje', models.ForeignKey(blank=True, db_column='id_viaje', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logistica.horario')),
                ('id_tipo', models.ForeignKey(blank=True, db_column='id_tipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.tipopasajero')),
            ],
            options={
                'db_table': 'pasaje',
                'managed': True,
                'unique_together': {('id_viaje', 'nro_asiento', 'placa_bus')},
            },
        ),
    ]
